// Salas de modelos 3D de los módulos (módulo ES). Cada sala muestra los equipos del tema con su ficha.
// Los datos normativos citados están verificados en 02_fuentes_verificadas/registro_fuentes.md (consulta 05/10/2026);
// donde no hay numeral verificado solo se menciona la norma relacionada, sin numeral.
// pieza: { k: kit|'props', c: clave, n: nombre, d: descripción, s?: escala }
export const MODULOS = {
  'primeros-auxilios': { titulo: 'Primeros auxilios', area: 'hospital', nom: 'NOM-030-STPS-2009 · LFT art. 504', color: 'verde', senal: 'primeros', kit: 'primeros-auxilios', piso: 'concreto',
    intro: 'Equipo básico para atender una emergencia mientras llega la ayuda profesional. No existe una NOM exclusiva de primeros auxilios: la LFT (art. 504 fr. I) obliga a tener material de curación y personal adiestrado, y la NOM-030-STPS-2009 organiza los servicios preventivos.',
    piezas: [
      { k: 'primeros-auxilios', c: 'botiquin', n: 'Botiquín', d: 'Material de curación disponible y revisado. La LFT (art. 504, fr. I) obliga al patrón a mantener medicamentos y material de curación.' },
      { k: 'primeros-auxilios', c: 'botiquin_pared', n: 'Botiquín de pared', d: 'Ubicado en lugar visible y señalizado con la señal verde de primeros auxilios (NOM-026-STPS-2008, Apéndice D 2).' },
      { k: 'primeros-auxilios', c: 'dea', n: 'DEA (desfibrilador automático externo)', d: 'Equipo que analiza el ritmo del corazón y, si corresponde, indica descargar. Se usa junto con la RCP de alta calidad (guías AHA 2025).' },
      { k: 'primeros-auxilios', c: 'vendas', n: 'Vendas', d: 'Para cubrir heridas y sujetar apósitos.' },
      { k: 'props', c: 'camilla', n: 'Camilla rígida (tabla)', d: 'Para inmovilizar y trasladar a una persona lesionada; se usa con correas.' },
      { k: 'props', c: 'collarin', n: 'Collarín cervical', d: 'Elemento de inmovilización del cuello; solo debe colocarlo personal capacitado.' },
      { k: 'props', c: 'cobija', n: 'Cobija térmica', d: 'Manta de emergencia que ayuda a conservar la temperatura del cuerpo.' },
      { k: 'primeros-auxilios', c: 'cama', n: 'Cama de recuperación', d: 'Área de descanso del puesto de primeros auxilios.' },
      { k: 'primeros-auxilios', c: 'silla_ruedas', n: 'Silla de ruedas', d: 'Para traslado de personas con movilidad limitada.' } ] },
  'extintores-fuego': { titulo: 'Extintores y fuego', area: 'proteccion', nom: 'NOM-002-STPS-2010', color: 'rojo', senal: 'extintor', kit: 'extintores-fuego', piso: 'placa_metal',
    intro: 'Tipos de extintor y clases de fuego. Según la Guía de referencia VII de la NOM-002-STPS-2010 (Tabla VII.1, no obligatoria): agua → fuego clase A; polvo químico seco ABC → clases A, B y C; bióxido de carbono (CO₂) → clases B y C.',
    piezas: [
      { k: 'props', c: 'extintor_pqs', n: 'Extintor PQS (ABC)', d: 'Polvo químico seco tipo ABC: fuegos clase A, B y C (NOM-002-STPS-2010, Guía VII, Tabla VII.1). Revisión mensual: manómetro en zona verde, sello sin violar (7.2).' },
      { k: 'props', c: 'extintor_co2', n: 'Extintor CO₂', d: 'Bióxido de carbono: fuegos clase B y C. No usar al aire libre o con corrientes de aire; en espacios cerrados reduce el oxígeno (Guía VII, VII.3.2 y VII.3.3).' },
      { k: 'props', c: 'extintor_agua', n: 'Extintor de agua', d: 'Agua: fuego clase A (sólidos que forman brasas). Nunca en equipos eléctricos energizados (clase C).' },
      { k: 'props', c: 'gabinete', n: 'Gabinete para extintor', d: 'Los extintores deben estar visibles, accesibles, libres de obstáculos y señalizados (NOM-002-STPS-2010, 7.2 b y c).' },
      { k: 'extintores-fuego', c: 'extintor_a', n: 'Extintor (modelo genérico)', d: 'Altura máxima de colocación: 1.50 m a la parte más alta del extintor (NOM-002-STPS-2010, 7.17 f).' },
      { k: 'extintores-fuego', c: 'hidrante', n: 'Hidrante', d: 'Equipo contra incendio fijo; se identifica con la señal roja de hidrante (NOM-026-STPS-2008, D.1.2).' },
      { k: 'extintores-fuego', c: 'tambo', n: 'Tambo metálico', d: 'Recipiente de líquidos: posible fuego clase B (líquidos combustibles o inflamables).' },
      { k: 'extintores-fuego', c: 'fogata', n: 'Fuego de práctica', d: 'Zona de práctica controlada. El entrenamiento para manejar extintores es teórico-práctico (NOM-002-STPS-2010, 11.2 a).', fuego: true },
      { k: 'extintores-fuego', c: 'caja', n: 'Material combustible', d: 'Papel, cartón y madera: fuego clase A.' } ] },
  alturas: { titulo: 'Trabajos en alturas', area: 'industria', nom: 'NOM-009-STPS-2011', color: 'amarillo', senal: 'caida', kit: 'alturas', piso: 'concreto',
    intro: 'Trabajo en altura: actividades a más de 1.80 m sobre el nivel de referencia, según la definición de la NOM-009-STPS-2011. Se usa un sistema personal para interrumpir caídas.',
    piezas: [
      { k: 'props', c: 'arnes', n: 'Arnés de cuerpo completo', d: 'Parte del sistema personal para interrumpir caídas: arnés, línea de vida o conector y punto de anclaje.' },
      { k: 'props', c: 'linea_vida', n: 'Línea de vida', d: 'Permite desplazarse conectado. Se inspecciona antes de cada uso.' },
      { k: 'props', c: 'anclaje', n: 'Punto de anclaje', d: 'Estructura a la que se conecta el sistema; debe resistir la carga de una caída.' },
      { k: 'props', c: 'andamio', n: 'Andamio tubular', d: 'Con plataforma completa, barandal y rodapié. El uso de andamios requiere autorización por escrito del patrón (NOM-009-STPS-2011).', s: .55 },
      { k: 'alturas', c: 'escalera', n: 'Escalera seccionada', d: 'Revisar peldaños y largueros antes de usarla; apoyarla en superficie firme.' },
      { k: 'alturas', c: 'escalera_fija', n: 'Escalera fija (marina)', d: 'Acceso vertical a techos y plataformas.' },
      { k: 'alturas', c: 'plataforma', n: 'Pasarela con barandal', d: 'Protección colectiva: barandales en bordes con riesgo de caída.' },
      { k: 'props', c: 'casco', n: 'Casco con barbiquejo', d: 'El barbiquejo evita que el casco se caiga durante el trabajo en altura.' },
      { k: 'alturas', c: 'anclaje', n: 'Anclaje con cable', d: 'Cable de acero con punto de conexión.' } ] },
  'espacios-confinados': { titulo: 'Espacios confinados', area: 'industria', nom: 'NOM-033-STPS-2015', color: 'amarillo', senal: 'prec_general', kit: 'espacios-confinados', piso: 'grava',
    intro: 'Espacio confinado: lugar con ventilación natural nula o deficiente, con medios de entrada y salida limitados, no diseñado para ocupación continua. La NOM-033-STPS-2015 los clasifica en tipo I y tipo II.',
    piezas: [
      { k: 'espacios-confinados', c: 'registro', n: 'Tapa de registro / pozo', d: 'Acceso típico a un espacio confinado: entrada limitada y ventilación deficiente.' },
      { k: 'espacios-confinados', c: 'tanque_grande', n: 'Tanque / cisterna', d: 'Interior de tanques: espacio confinado; se monitorea la atmósfera antes de entrar.' },
      { k: 'props', c: 'tripie', n: 'Tripié de rescate', d: 'Permite el rescate vertical del trabajador conectado con arnés.' },
      { k: 'props', c: 'detector', n: 'Detector de gases', d: 'Muestreo y monitoreo para detectar atmósferas peligrosas antes y durante el trabajo.' },
      { k: 'props', c: 'ventilador_ducto', n: 'Ventilador con ducto', d: 'Ventilación forzada para renovar el aire del espacio.' },
      { k: 'espacios-confinados', c: 'ventilador', n: 'Extractor', d: 'Extracción de aire contaminado.' },
      { k: 'espacios-confinados', c: 'tubo_valvula', n: 'Tubería con válvula', d: 'Antes de entrar se aíslan las tuberías que alimentan el espacio.' },
      { k: 'espacios-confinados', c: 'mascarilla', n: 'Respirador', d: 'Protección respiratoria según el riesgo evaluado (NOM-017-STPS-2024).' } ] },
  'seguridad-electrica': { titulo: 'Seguridad eléctrica', area: 'industria', nom: 'NOM-029-STPS-2011', color: 'amarillo', senal: 'electrico', kit: 'seguridad-electrica', piso: 'concreto',
    intro: 'El mantenimiento de instalaciones eléctricas solo lo realiza personal capacitado (NOM-029-STPS-2011). Equipo y protección para trabajar con riesgo eléctrico.',
    piezas: [
      { k: 'seguridad-electrica', c: 'tablero', n: 'Tablero eléctrico', d: 'Debe estar señalizado con la advertencia de riesgo eléctrico (NOM-026-STPS-2008, C.7) y con el frente libre.' },
      { k: 'seguridad-electrica', c: 'tablero_b', n: 'Tablero eléctrico doble', d: 'Antes de intervenir: desenergizar, bloquear, etiquetar y comprobar ausencia de tensión.' },
      { k: 'seguridad-electrica', c: 'caja_fusibles', n: 'Caja de fusibles', d: 'Elementos de protección del circuito.' },
      { k: 'seguridad-electrica', c: 'palanca_doble', n: 'Interruptor de palanca', d: 'Punto de corte de energía; se bloquea con candado durante el mantenimiento.' },
      { k: 'props', c: 'tapete', n: 'Tapete dieléctrico', d: 'Aislamiento del piso frente a tableros.' },
      { k: 'props', c: 'guantes', n: 'Guantes dieléctricos', d: 'Protección de manos para trabajo con riesgo eléctrico, según la clase de tensión.' },
      { k: 'props', c: 'careta', n: 'Careta', d: 'Protección de cara (NOM-026-STPS-2008, B.10 señal de obligación).' },
      { k: 'props', c: 'herramienta', n: 'Herramienta aislada', d: 'Mangos con aislamiento para trabajo eléctrico.' },
      { k: 'seguridad-electrica', c: 'poste', n: 'Poste eléctrico', d: 'Líneas aéreas: el mantenimiento en líneas también está dentro del campo de la NOM-029-STPS-2011.' } ] },
  loto: { titulo: 'Bloqueo y etiquetado (LOTO)', area: 'industria', nom: 'NOM-004-STPS-1999 · NOM-029-STPS-2011', color: 'azul', senal: 'guantes', kit: 'loto', piso: 'placa_metal',
    intro: 'Bloqueo y etiquetado de fuentes de energía antes del mantenimiento de maquinaria e instalaciones (temas de la NOM-004-STPS-1999 y de la NOM-029-STPS-2011). Cada persona coloca su propio candado.',
    piezas: [
      { k: 'props', c: 'estacion', n: 'Estación de bloqueo', d: 'Concentra candados, etiquetas y pinzas en un lugar visible.' },
      { k: 'props', c: 'candado', n: 'Candado personal', d: 'Un candado y una llave por persona: solo quien lo colocó lo retira.', s: 3 },
      { k: 'props', c: 'pinza', n: 'Pinza multibloqueo', d: 'Permite que varias personas bloqueen el mismo punto de energía.', s: 3 },
      { k: 'props', c: 'etiqueta', n: 'Etiqueta de bloqueo', d: 'Identifica quién bloqueó y por qué; acompaña al candado.', s: 2.5 },
      { k: 'loto', c: 'tablero', n: 'Interruptor principal', d: 'Fuente de energía eléctrica a bloquear.' },
      { k: 'loto', c: 'palanca', n: 'Interruptor de corte', d: 'Se lleva a posición de apagado y se bloquea.' },
      { k: 'loto', c: 'valvula', n: 'Válvula', d: 'Energía de fluidos (hidráulica, neumática, vapor): también se bloquea.' },
      { k: 'loto', c: 'maquina', n: 'Máquina', d: 'Equipo que se va a intervenir: verificar energía cero antes de trabajar.' },
      { k: 'loto', c: 'banda', n: 'Banda transportadora', d: 'Partes en movimiento: requieren protectores y bloqueo para mantenimiento (NOM-004-STPS-1999).' } ] },
};
export const SALAS = Object.entries(MODULOS).map(([id, m]) => ({ id, ...m }));
